version: '2'

networks:
  wan:
    external: true
  monitoring:

services:

  telegraf:
    image: francescou/rpi-telegraf:1.4.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - monitoring
    links:
      - influxdb
    restart: always

  influxdb:
    image: hypriot/rpi-influxdb:1.2.2
    networks:
      - monitoring
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - ./data/influxdb:/data
    environment:
      - ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_INIT_PWD=${INFLUXDB_PASSWORD}
      - PRE_CREATE_DB=${PRE_CREATE_DB}
    restart: always
 
  grafana:
    image: fg2it/grafana-armhf:v4.6.2
    networks:
      - monitoring
      - wan
    ports:
      - "${GRAFANA_PORT}:3000"
    links:
      - influxdb
    volumes:
      - ./data/grafana:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.backend=grafana"
      - "traefik.docker.network=wan"
      - "traefik.port=${GRAFANA_PORT}"
      - "traefik.frontend.rule=Host:${HOSTNAME}"
    restart: always
